### ISSUE TITLE
Media block not retrieving correct images

### ISSUE THREAD

**Issue by ssjowowo** [tzyganu/Switcher#115]
Hi guys,

I have an issue where I have 2 configurable attributes: color and size. 

For each combination and simple product, I have separate images. When I change the color, the media block gets rendered correctly (i.e. the correct images are retrieved for the color selected)

When I then go and change the size, the media block retrieved contains the correct images for the size selected but not for the color. This happens the other way too. 

It seems that the previous selection is not taken into consideration when rendering the media block. Is there any way that I am doing something wrong?

Thanks for the plugin btw :)

**Comment by ssjowowo** [comment]
Sorry forgot to include the URL to check:  http://www.aquariusjewels.com/index.php/rings/wedding/wedding-ring-4.html

**Comment by tzyganu** [comment]
@ssjowowo Thanks for reporting this. I will investigate and get back to you with an answer. All I can say for now is that the problem can be reproduced.

**Comment by tzyganu** [comment]
@ssjowowo I just released a new version. 2.3.0. I did some tests an now it looks ok, but since you already have everything configured with a lot of different images for simple products, your confirmation would help me a lot.  
I will close this issue for now and if it reproduces on the new version feel free to comment here and I will reopen it.

**Comment by ssjowowo** [comment]
Unfortunately it doesn't seem to work. Please take a look here:

http://www.aquariusjewels.com/index.php/rings/wedding/dwr1.html

I have added new attributes from scratch with new images but still nothing.
Now the behaviour seems even stranger. Please note that I have different
images for Metal Color1 and Width1 fields.

If you need anything else from my side, please let me know.

Thanks

**Comment by tzyganu** [comment]
@ssjowowo Damn it. I will give it an other try. Thanks.

**Comment by andros89cy** [comment]
Hello Marius 

Thanks for your extension and your help! I can give you admin panel or ftp access if you need better understanding of the issue. Please send me an email to aquariusjewels1983@gmail.com if you need those access.

Thanks

**Comment by tzyganu** [comment]
I'm hoping I can fix it without accessing your admin. If I need it, I will contact you. In the mean time, if you don't want your e-mail address public in here, you can delete it from your comment above. I've written it down just in case.

**Comment by tzyganu** [comment]
I did some changes. See if version 2.3.1 works as you expect it to work. 
I also improved the performance a bit.

**Comment by andros89cy** [comment]
i will check it now and i will let you know man !
Thanks !

**Comment by andros89cy** [comment]
seems the issue still the same.
Thanks

**Comment by tzyganu** [comment]
Yeah. back to the drawing board. The odd thing is that I cannot reproduce it on my side. I also see that you have some extension that from time to time, when changing the product configuration, makes an ajax call to `oi/ajax/co`. Most probably it has nothing to do with the problem, but it wouldn't hurt to try it with the extension disabled.  
Thanks for your patience and the help you provide for making this extension better. 
I will post back when I have different results.

**Comment by tzyganu** [comment]
This time it has to be right. I did some changes to the `js/easylife_switcher/product.js` and it seams to work. Since there were only client side changes, I used your website to test and I think I got the right results. 
Please let me know if it works for you. 
If it doesn't work, I'll go join a mental institution. :smile: 
Forget about the ajax call I mentioned in the previous comment. It has nothing to do with the extension.

**Comment by andros89cy** [comment]
You don't need to join a mental institution because Y-O-U  A-R-E  A  P-R-O-F-F-E-S-O-R !!!!!!
Working perfect man!
Thanks a lot !!
Is anything that i can do for you? How much do i owe you ?

**Comment by tzyganu** [comment]
Huh. I'm glad it finally turned out fine.  
You owe me nothing. If someone owes something it me, for your help and patience. I couldn't have done it without you. 
I say "call it even".  :smile: 
if you find any other issue please report them. 
Thanks.

**Comment by adiemen** [comment]
Hi.. @tzyganu sory I am newbie for devlopment magento, i used your extension but it's not working be well. I have problem it's cannot call product swithcer on product configurable but it's can call image attribute selection. I am use Magento 1.9.1. Please help and thanks.
